// import React  from "react";

// function Opportunity()
// {


//     const Opportunity = [
      
//           {
//             title :"Chartered Accountant Common Proficiency Test "   ,
//             description :"Conducted by The Institute of Chartered Accountants of India (ICAI).Relevant for pursuing Chartered Accountancy." ,
//             url : "https://icaiexam.icai.org/faq_verification.php"
//           },{
//             title :"CS Executive Entrance Test (CSEET) "   ,
//             description :"Conducted by The Institute of Company Secretary of India (ICSI)." ,
//             url : "https://www.icsi.edu/exam/"
//           },
//           {
//             title :"LIC-AAO (Life Insurance Corporation - Assistant Administrative Officer) "  ,
//             description :" A government exam relevant for commerce graduates. Offers opportunities in the insurance sector.                        " ,
//             url : "https://www.adda247.com/jobs/lic-aao-notification/"
//           },
//           {
//             title :"UGC-NET (University Grants Commission - National Eligibility Test) "  ,
//             description :" Not specific to commerce but open to all postgraduate students. Qualifying this exam opens doors to teaching and research positions. " ,
//             url : "https://ugcnet.nta.nic.in/"
//           },
//           {
//             title :"Civil Services Exam "  ,
//             description :"Conducted by the Union Public Service Commission (UPSC).Not exclusive to commerce students, but a prestigious option.Offers various administrative roles in the government. " ,
//             url : "https://upsc.gov.in/"
//           },
//           {
//             title :" IPPB Exam (India Post Payments Bank)"  ,
//             description :"  Relevant for banking and financial services. Conducted by India Post Payments Bank. " ,
//             url : "https://www.ippbonline.com/web/ippb/current-openings"
//           },
//           {
//             title :" CTET (Central Teacher Eligibility Test)   "  ,
//             description :" For those interested in teaching positions.Conducted by the Central Board of Secondary Education (CBSE). " ,
//             url : "https://ctet.nic.in/"
//           },




//     ]

//     return
//     (
//         <>
          

//         </>
//     )
// }
// export default Opportunity;